name: Codeowners
on:
  push:
    branches:
      - main
jobs:
  codeowners:
    name: codeowners
    runs-on: ubuntu-latest
    steps:
      - name: Fetch team members
        run: |
          curl --request GET \
          --url https://api.github.com/orgs/taxibeat/teams \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --fail

      - name: Check out source code
        uses: actions/checkout@v3
