name: Codeowners
on:
  push:
    branches:
      - main
jobs:
  codeowners:
    name: codeowners
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Fetch existing and new code owners
        id: fetch-code-owners
        run: |
          EXISTING_CODEOWNERS=$(cat .github/CODEOWNERS)
          echo "::set-output name=EXISTING_CODEOWNERS::$EXISTING_CODEOWNERS"
          NEW_CODEOWNERS=$(curl --request GET --url https://api.github.com/orgs/945s/teams/test-1/members --header 'authorization: Bearer ${{ secrets.REPO_TOKEN }}' --fail | jq -r '.[].login' | sort | awk '{ printf "@%s ", $1 }')
          echo "::set-output name=NEW_CODEOWNERS::$NEW_CODEOWNERS"

      - name: Modify CODEOWNERS
#        if: ${{ steps.fetch-code-owners.EXISTING_CODEOWNERS != steps.fetch-code-owners.NEW_CODEOWNERS }}
        run: echo "*       ${{ steps.fetch-code-owners.outputs.NEW_CODEOWNERS }}" > .github/CODEOWNERS

      - name: Create PR
        if: ${{ steps.fetch-code-owners.EXISTING_CODEOWNERS != steps.fetch-code-owners.NEW_CODEOWNERS }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update CODEOWNERS
          title: Update CODEOWNERS
          branch: update-codeowners