name: Codeowners
on:
  push:
    branches:
      - main
jobs:
  codeowners:
    name: codeowners
    runs-on: ubuntu-latest
    steps:
      - name: Fetch team members
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail

      - name: Check out source code
        uses: actions/checkout@v3
